# Config file for the VLLM runner

model:
  id: "lmdeploy-minicpmv2d6-awq-visual-classifier"
  user_id: ""
  app_id: ""
  model_type_id: "visual-classifier"

build_info:
  python_version: "3.10"

inference_compute_info:
  cpu_limit: "4"
  cpu_memory: "16Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G"]
  accelerator_memory: "24Gi"

checkpoints:
  type: "huggingface"
  repo_id: "jfiekdjdk/MiniCPM-V-2_6-awq" # Or any vlm hf id supported by lmdeploy
  hf_token: "your token"

concepts:
- id: '0-2'
  name: 0-2
- id: '3-9'
  name: 3-9
- id: '10-19'
  name: 10-19
- id: '20-29'
  name: 20-29
- id: '30-39'
  name: 30-39
- id: '40-49'
  name: 40-49
- id: '50-59'
  name: 50-59
- id: '60-69'
  name: 60-69
- id: 'more-than-70'
  name: more than 70