dataset_id: ''
dataset_version_id: ''
concepts: []
train_params:
  invalid_data_tolerance_percent: 5.0
  template: HF_GPTNeo_125m_lora
  model_config:
    pretrained_model_name: EleutherAI/gpt-neo-125m
    torch_dtype: torch.float32
    problem_type: multi_label_classification
  peft_config:
    r: 16.0
    peft_type: LORA
    task_type: SEQ_CLS
    lora_dropout: 0.1
    inference_mode: false
    lora_alpha: 16.0
  tokenizer_config: {}
  trainer_config:
    auto_find_batch_size: true
    num_train_epochs: 1.0
inference_params:
  select_concepts: []
