workflow:
  id: wf-prompter-llm
  nodes:
    - id: prompter
      model:
          model_id: prompter
          model_type_id: prompter
          description: 'Prompter Model'
          output_info:
            params:
              prompt_template: 'Classify sentiment between postive and negative for the text {data.text.raw}'

    - id: llm
      model:
          user_id: openai
          model_id: GPT-3_5-turbo
          app_id: chat-completion

      node_inputs:
        - node_id: prompter
