clarifai_model:
  clarifai_model_id: ''
  clarifai_user_app_id: ''
  description: ''
  inference_parameters: []
  labels:
  - background
  - hat
  - hair
  - sunglass
  - upper-clothes
  - skirt
  - pants
  - dress
  - belt
  - left-shoe
  - right-shoe
  - face
  - left-leg
  - right-leg
  - left-arm
  - right-arm
  - bag
  - scarf
  type: visual-segmenter
serving_backend:
  triton:
    max_batch_size: 4
