clarifai_model:
  clarifai_model_id: ''
  clarifai_user_app_id: ''
  description: ''
  inference_parameters: []
  labels:
  - Negative
  - Neutral
  - Positive
  type: text-classifier
serving_backend:
  triton:
    max_batch_size: 4
