# This is the sample config file for the GOT OCR2.O model.

model:
  id: "got-ocr-2_0"
  user_id: "user_id"
  app_id: "app_id"
  model_type_id: "image-to-text"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "3Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA*"]
  accelerator_memory: "3Gi"

checkpoints:
  type: "huggingface"
  repo_id: "stepfun-ai/GOT-OCR2_0"
