# Config file for the VLLM runner

model:
  id: "lmdeploy-minicpm2d6-openvocab-vis-classifier"
  user_id: ""
  app_id: ""
  model_type_id: "visual-classifier"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: "4"
  cpu_memory: "16Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G"]
  accelerator_memory: "24Gi"

concepts:
- id: none
  name: none