nodepool:
  id: "test-nodepool"
  compute_cluster:
    id: "test-compute-cluster"
  description: "First nodepool in AWS in a proper compute cluster"
  instance_types:
    - id: "g5.xlarge"
  node_capacity_type:
    capacity_types:
      - 1
      - 2
  max_instances: 1
