# This is the sample config file for the llama model.

model:
  id: "miniCPM-2_6"
  user_id: "user_id"
  app_id: "app_id"
  model_type_id: "multimodal-to-text"

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "12Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G"]
  accelerator_memory: "12Gi"

checkpoints:
  type: "huggingface"
  repo_id: "jfiekdjdk/MiniCPM-V-2_6-awq"
  hf_token: "hf_token"
