OCR = "<OCR>"
CAPTION = "<CAPTION>"
DETAILED_CAPTION = "<DETAILED_CAPTION>"
MORE_DETAILED_CAPTION = "<MORE_DETAILED_CAPTION>"
REGION_TO_CATEGORY = "<REGION_TO_CATEGORY>"
REGION_TO_DESCRIPTION = "<REGION_TO_DESCRIPTION>"


OD = "<OD>"
CAPTION_TO_PHRASE_GROUNDING = "<CAPTION_TO_PHRASE_GROUNDING>"
DENSE_REGION_CAPTION = "<DENSE_REGION_CAPTION>"
REGION_PROPOSAL = "<REGION_PROPOSAL>"
OPEN_VOCABULARY_DETECTION = "<OPEN_VOCABULARY_DETECTION>"
OCR_WITH_REGION = "<OCR_WITH_REGION>"


REFERRING_EXPRESSION_SEGMENTATION = "<REFERRING_EXPRESSION_SEGMENTATION>"
REGION_TO_SEGMENTATION = "<REGION_TO_SEGMENTATION>"


TASKS = [
  CAPTION,
  DETAILED_CAPTION,
  MORE_DETAILED_CAPTION,
  CAPTION_TO_PHRASE_GROUNDING,
  OD,
  DENSE_REGION_CAPTION,
  REGION_PROPOSAL,
  REFERRING_EXPRESSION_SEGMENTATION,
  REGION_TO_SEGMENTATION,
  OPEN_VOCABULARY_DETECTION,
  REGION_TO_CATEGORY,
  REGION_TO_DESCRIPTION,
  OCR,
  OCR_WITH_REGION,
]


CAPTION_TASKS = [
  OCR,
  CAPTION,
  DETAILED_CAPTION,
  MORE_DETAILED_CAPTION,
  REGION_TO_CATEGORY,
  REGION_TO_DESCRIPTION,
]

DETECTION_TASKS = [
  OD,
  CAPTION_TO_PHRASE_GROUNDING,
  DENSE_REGION_CAPTION,
  REGION_PROPOSAL,
  OPEN_VOCABULARY_DETECTION,
]

REGION_OCR_TASKS = [OCR_WITH_REGION]

SEGMENTATION_TASKS = [
  REFERRING_EXPRESSION_SEGMENTATION,
  REGION_TO_SEGMENTATION,
]

HAS_REGION_INPUT_TASK = [
  REGION_TO_SEGMENTATION,
  REGION_TO_CATEGORY,
  REGION_TO_DESCRIPTION
]