# Config file for the VLLM runner

model:
  id: "lmdeploy-llama3_2-1b-instruct"
  user_id: "user-id"
  app_id: "app-id"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.10"

inference_compute_info:
  cpu_limit: "2"
  cpu_memory: "12Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G"]
  accelerator_memory: "24Gi"

checkpoints:
  type: "huggingface"
  repo_id: "meta-llama/Llama-3.2-1B-Instruct"
  hf_token: "token"
