# Config file for the VLLM runner

model:
  id: "random-concept-text-classifier-2"
  user_id: ""
  app_id: ""
  model_type_id: "text-classifier"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "2Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G"]
  accelerator_memory: "1Gi"

concepts:
- id: none
  name: none