# Config file for the VLLM runner

model:
  id: "model_id"
  user_id: "user_id"
  app_id: "app_id"
  model_type_id: "text-to-text"

build_info:
  python_version: "3.10"

inference_compute_info:
  cpu_limit: "1"
  cpu_memory: "16Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G"]
  accelerator_memory: "18Gi"

checkpoints:
  type: "huggingface"
  repo_id: "mistralai/Mistral-7B-Instruct-v0.2"
  hf_token: "hf_token"
