# This is the sample config file for the image-detection model.

model:
  id: "florence2-openvocab-visual-detector"
  user_id: ""
  app_id: ""
  model_type_id: "visual-detector"

build_info:
  python_version: "3.12"

inference_compute_info:
  cpu_limit: "2"
  cpu_memory: "8Gi"
  num_accelerators: 1
  accelerator_type: ["NVIDIA-A10G"]
  accelerator_memory: "20Gi"


checkpoints:
  type: "huggingface"
  repo_id: "microsoft/Florence-2-large"
  hf_token: "hf_token"

concepts:
  - id: none
    name: none