model:
  id: "video_streaming_test"
  user_id: "user"
  app_id: "app"
  model_type_id: "video-to-text"  # TODO?

build_info:
  python_version: "3.11"

inference_compute_info:
  cpu_limit: "2"
  cpu_memory: "1Gi"
  num_accelerators: 0
