clarifai_model:
  clarifai_model_id: ''
  clarifai_user_app_id: ''
  description: ''
  inference_parameters: []
  labels:
  - 0-2
  - 3-9
  - 10-19
  - 20-29
  - 30-39
  - 40-49
  - 50-59
  - 60-69
  - more than 70
  type: visual-classifier
serving_backend:
  triton:
    max_batch_size: 4
